/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleJDK11;

public class App {
    public String getGreeting() {
        String x = "Hellooow";
        return x;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.print(NewClassJDK11.estasix());
        System.out.print("Ahora sí");
    }
}
